processed 8 tasks

task 4 'run'. lines 10-53:
{
  "gas_used": 3816005,
  "status": "Executed"
}

task 5 'run'. lines 55-94:
{
  "gas_used": 42303191,
  "status": "Executed"
}

task 6 'run'. lines 96-113:
{
  "gas_used": 5787302,
  "status": "Executed"
}

task 7 'run'. lines 115-136:
{
  "gas_used": 42817217,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x29ce635e538f628632963e92ed506d25",
          "name": "zion_cross_chain_manager"
        }
      },
      "abort_code": "15"
    }
  }
}
