processed 11 tasks

task 5 'run'. lines 26-63:
{
  "gas_used": 3173723,
  "status": "Executed"
}

task 6 'run'. lines 65-82:
{
  "gas_used": 5626345,
  "status": "Executed"
}

task 7 'run'. lines 84-100:
{
  "gas_used": 1464101,
  "status": "Executed"
}

task 8 'run'. lines 102-115:
{
  "gas_used": 7049333,
  "status": "Executed"
}

task 9 'run'. lines 117-138:
{
  "gas_used": 4126014,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0xf08ac0c1c6c8f2be528b358247550540",
          "name": "zion_cross_chain_manager"
        }
      },
      "abort_code": "17"
    }
  }
}

task 10 'run'. lines 140-158:
{
  "gas_used": 1945000,
  "status": "Executed"
}
