processed 6 tasks

task 3 'run'. lines 7-21:
{
  "gas_used": 22857562,
  "status": "Executed"
}

task 4 'run'. lines 23-31:
{
  "gas_used": 83272,
  "status": "Executed"
}

task 5 'run'. lines 33-50:
{
  "gas_used": 33375,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x416b32009fe49fcab1d5f2ba0153838f",
          "name": "CrossChainGlobal"
        }
      },
      "abort_code": "26369"
    }
  }
}
