processed 8 tasks

task 4 'run'. lines 23-56:
{
  "gas_used": 22084442,
  "status": "Executed"
}

task 5 'run'. lines 58-69:
{
  "gas_used": 33144,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x416b32009fe49fcab1d5f2ba0153838f",
          "name": "CrossChainData"
        }
      },
      "abort_code": "25857"
    }
  }
}

task 6 'run'. lines 71-82:
{
  "gas_used": 28328078,
  "status": "Executed"
}

task 7 'run'. lines 84-112:
{
  "gas_used": 22097263,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x416b32009fe49fcab1d5f2ba0153838f",
          "name": "CrossChainManager"
        }
      },
      "abort_code": "27137"
    }
  }
}
