processed 6 tasks

task 3 'run'. lines 7-21:
{
  "gas_used": 25688955,
  "status": "Executed"
}

task 4 'run'. lines 23-31:
{
  "gas_used": 83272,
  "status": "Executed"
}

task 5 'run'. lines 33-50:
{
  "gas_used": 33375,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0xe52552637c5897a2d499fbf08216f73e",
          "name": "CrossChainGlobal"
        }
      },
      "abort_code": "26369"
    }
  }
}
