processed 10 tasks

task 3 'run'. lines 7-41:
{
  "gas_used": 22084442,
  "status": "Executed"
}

task 4 'run'. lines 43-59:
{
  "gas_used": 31409,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0xe52552637c5897a2d499fbf08216f73e",
          "name": "LockProxy"
        }
      },
      "abort_code": "27905"
    }
  }
}

task 5 'run'. lines 62-73:
{
  "gas_used": 28328078,
  "status": "Executed"
}

task 6 'run'. lines 75-105:
{
  "gas_used": 22107137,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0xe52552637c5897a2d499fbf08216f73e",
          "name": "CrossChainManager"
        }
      },
      "abort_code": "27137"
    }
  }
}

task 7 'run'. lines 108-117:
{
  "gas_used": 97919,
  "status": "Executed"
}

task 8 'run'. lines 119-128:
{
  "gas_used": 88222,
  "status": "Executed"
}

task 9 'run'. lines 131-147:
{
  "gas_used": 139780,
  "status": "Executed"
}
